version: "3.9"

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped

    ports:
      - "8096:8096"

    environment:
      - TZ=Asia/Dhaka

    volumes:
      - jellyfin_config:/config
      - jellyfin_cache:/cache

      - E:/Movies:/media/movies:ro
      - E:/tv-shows:/media/tv-shows:ro
      - E:/anime:/media/anime:ro
      - E:/photos:/media/photos:ro

  caddy:
    image: caddy:2
    container_name: moviedock-caddy
    restart: unless-stopped

    ports:
      - "80:80"

    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  jellyfin_config:
  jellyfin_cache:
  caddy_data:
  caddy_config: